### PR TITLE
Fix ejected dev server and env var setting on windows. Fixes #22

### LINKED ISSUE #22: Ejected scripts fail on Windows cmd
When you `eject` the 3 npm scripts `start`, `test` and `build` are not portable to Windows cmd

https://github.com/cyclejs-community/create-cycle-app-flavors/blob/master/packages/cycle-scripts-one-fits-all/scripts/eject.js#L15-L17

the `NODE_ENV=development ` prefix is bash (etc) specific

I suggest using the `cross-env` package, Install it and simply prefix each existing script with `cross-env `, like so

```sh
start: 'cross-env NODE_ENV=development webpack --config webpack.config.js',
test: 'cross-env NODE_ENV=test nyc mocha-webpack --timeout=100000 --colors --webpack-config webpack.config.test.js test/**/*.test.*',
build: 'cross-env NODE_ENV=production webpack --config webpack.config.js'
```

If you agree I'll submit a PR

### PR DESCRIPTION
**Pull request by SteveALee**
@jvanbruegge here's a PR.

I forgot was a community member hence my forgetting to fork :)

### CODE REVIEW

**Comment by SteveALee** [comment]
I tested on cmd and Bash for Ubuntu on Windows

**Comment by jvanbruegge** [comment]
I will merge it now, but I can't release it today

**Comment by SteveALee** [comment]
On 7 May 2017 13:52, "Jan van Brügge" <notifications@github.com> wrote:

I will merge it now, but I can't release it

That's fine. Thanks

**Comment by jvanbruegge** [comment]
Published now as v 2.1.0

**Pull request merged**
