### PR TITLE
Remove babel from build and start config

### LINKED ISSUE #26: [cycle-scripts-one-fits-all] request for doc on TS + Babel
This flavor's README says:

> ES6 or Typescript 2.1 configured with:
>  * TypeScript target: ES6 transpiles to ES6 with lib: DOM,ES6,DOM.Iterable,ScriptHost and piped through Babel
>  * Babel targets ES5 with ES2015 preset

This (obviously) works, but can be quite surprising to someone coming in from other TypeScript use. TypeScript can compile most ES2015 (and many beyond) to ES5 nowadays, without any help from Babel. Babel adds time and (very) numerous dependencies. I assume this is needed, but haven't been able to find a reason why yet.

How about a sentence or two in the README about *why* TS+Babel?

(If someone wants to just write a sentence here, I am happy tidy up the words and make a doc PR.)

### PR DESCRIPTION
**Pull request by jvanbruegge**
fixes: #26 #21 #25

Babel is still needed, because Istanbul will not generate a coverage that is remapped with source maps

### CODE REVIEW

**Comment by jvanbruegge** [comment]
I also moved the entry definition into the customizable webpack config and added the tsconfig to the folder, so editors can pick up the config too.

**Comment by kylecordes** [comment]
Tsconfig: excellent, I was missing this.

Istanbul: Over in the Angular world, I think Angular CLI got things working with:

https://github.com/webpack-contrib/istanbul-instrumenter-loader

**Comment by jvanbruegge** [comment]
I tried that too, but
1. it's also using babel in the background
2. the coverage would not be able to load the source map

**Comment by SteveALee** [comment]
Does that mean that with the current Babel config the coverage is based on the es6 output from TS and not the source? They probably map fairly close but could still be differences.

Node-tap does coverage but I just checked and it uses NYC / istanbul.

**Comment by jvanbruegge** [comment]
Yes and no. The coverage is generated with the ES6 output, but afterwards mapped back to typescript via source maps. You can run `npm test` and open `coverage/index.html`
You will see Typescript coverage

**Comment by SteveALee** [comment]
Does this Help? https://github.com/istanbuljs/nyc/issues/176

**Comment by jvanbruegge** [comment]
I tried that, but as said, the loader still uses babel under the hood, and the mapping did not work

**Comment by SteveALee** [comment]
Oh well.

FYI a new minifier on the block - https://github.com/Rich-Harris/butternut

**Comment by SteveALee** [comment]
I thought i'd check what TS does itself as it's written in TS itself. Seems it [uses istanbul via mocha](https://github.com/Microsoft/TypeScript/blob/72feaad893edaee561fb36af8d467b8cf03118cf/Gulpfile.ts#L840) so not much help here.

**Comment by kylecordes** [comment]
I looked briefly at Angular CLI for this, since they no doubt went through similar issues. I looked at the installed set of transitive dependencies. It appear from such inspection, that it somehow gets the job done (coverage check via Istanbul) bringing in only a very small number of babel-* packages. I might be misreading somehow, but if this Cycle tooling could achieve a similar result it would be very nice.

(Maybe they compile TS->ES2016, then ES2015->ES5, both using the TS compiler or something like that? Somehow they avoid, even transitively, bringing in the big pile of babel-*.)

**Comment by jvanbruegge** [comment]
With this PR the only babel dependencies are `babel-core` and `babel-plugin-istanbul` and they are only active when running `npm test`

**Comment by kylecordes** [comment]
Ah, great. I haven't npm installed the PR code to see that. (Babel package transitive deps aren't quite obvious by inspection.)

**Comment by jvanbruegge** [comment]
Those were the ones directly required. The transient ones are:
```
babylon
babel-types
babel-runtime
babel-messages
babel-traverse
babel-code-frame
babel-template
babel-generator
babel-helpers
```
But that's still a lot less than before :)
And the loader would have similar dependencies, because it depends directly on 4 of them and they depend on each other

**Comment by jvanbruegge** [comment]
Published as `3.0.0`

**Comment by SteveALee** [comment]
How I wish I hadn't ejected now :)

**Comment by jvanbruegge** [comment]
you would have to manually copy over anyway. The `3.0.0` is breaking and needs the template that is created on install.
You can create a new folder with 3.0, then copy over your sources and tests and be pre-ejected again.
You would have to do this for a non-ejected system too

**Comment by jvanbruegge** [comment]
You have to manually merge `package.json`
All in all it is not hard, I did it myself just now, from custom webpack config to my flavor

**Comment by SteveALee** [comment]
OK, thanks. 
Should put this a comment in the release notes an/or README

**Comment by SteveALee** [comment]
Oh, I noticed the semvers in package.json are not latest, but still match latest in most cases.
Do you have a policy for when they are updated? Every release? Just when wanted?
I can raise this as another issue if you like - being lazy

**Comment by SteveALee** [comment]
I used npm-check-updates

**Comment by kylecordes** [comment]
npm-check-updates is great - but only gets you as far as semver will allow by default. You can do `ncu -u -a` to get to the very latest, but them of course some testing is needed to see if anything broke.

**Comment by jvanbruegge** [comment]
I use `ncu` myself, but the dependencies of the template are declared in `init.js`, so `ncu` can't check this.
I updated them in `3.0.1`

**Pull request merged**
