### PR TITLE
[cycle-scripts-one-fits-all] Add explanatory comment for defaultSinks()

### PR DESCRIPTION
**Pull request by SteveALee**
Took me quite a while to figure out why you were doing this so a comment might help others.

### CODE REVIEW

**Comment by jvanbruegge** [comment]
Your explanation was not entirely correct, onionify will provide whatever we will provide.
The reason for the `Partial<>` is that you don't have to use all drivers in every component. Some might use DOM only, others multiple. I added the comment myself: https://github.com/cyclejs-community/create-cycle-app-flavors/commit/5de8529a4749e07877f1255e45c3a392de139d39

**Comment by jvanbruegge** [comment]
published in `3.1.1`

**Comment by SteveALee** [comment]
Ah, yes. My explanation was based on the type error caused by substituting defaultSinks with main. I see now that was more a symptom than the reason for setting defaults.:) 

I get it that a component can return a sent of sinks that have no relationship to its sources (and onionify follows that). But the cycle run patches things up so it expects the sink keys to match the source keys (drivers) - even if not actually returned by the component. I forgot that I'd hit that myself without types.

Your new code is an improvement and more generic. But it is pretty dense :) However, dense code means less bugs lurking. I don't see why  it is `[n]` though and not `n`? I also wonder if `Sources` should not be `RootSources`? An example child component might clarify things too - or make it more complicated.

It's taking a while to internalise generics and type inference despite yeas of deep C++ experience. TS does it differently.

Thanks for all your help.

**Comment by SteveALee** [comment]
> I don't see why it is [n] though and not n

http://es6-features.org/#ComputedPropertyNames

**Comment by jvanbruegge** [comment]
It's not RootSources as the sources are the same for all components, they will always be defined

**Comment by jvanbruegge** [comment]
And btw, `[n]` works pre-ES6, just not `[n + "hello"] `

**Comment by SteveALee** [comment]
> It's not RootSources as the sources are the same for all components, they will always be defined

I was going to say not so, but I no see it is and a component just ignores those it does need :)

**Pull request closed without merging**
